# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/203/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/203/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/roni/Downloads/assembler (1)"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/roni/Downloads/assembler (1)/cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/203/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/203/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/roni/Downloads/assembler (1)/cmake-build-debug/CMakeFiles" "/home/roni/Downloads/assembler (1)/cmake-build-debug//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/roni/Downloads/assembler (1)/cmake-build-debug/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assembler

# Build rule for target.
assembler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assembler
.PHONY : assembler

# fast build rule for target.
assembler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/build
.PHONY : assembler/fast

FirstTrans.o: FirstTrans.c.o
.PHONY : FirstTrans.o

# target to build an object file
FirstTrans.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/FirstTrans.c.o
.PHONY : FirstTrans.c.o

FirstTrans.i: FirstTrans.c.i
.PHONY : FirstTrans.i

# target to preprocess a source file
FirstTrans.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/FirstTrans.c.i
.PHONY : FirstTrans.c.i

FirstTrans.s: FirstTrans.c.s
.PHONY : FirstTrans.s

# target to generate assembly for a file
FirstTrans.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/FirstTrans.c.s
.PHONY : FirstTrans.c.s

SecondTrans.o: SecondTrans.c.o
.PHONY : SecondTrans.o

# target to build an object file
SecondTrans.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/SecondTrans.c.o
.PHONY : SecondTrans.c.o

SecondTrans.i: SecondTrans.c.i
.PHONY : SecondTrans.i

# target to preprocess a source file
SecondTrans.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/SecondTrans.c.i
.PHONY : SecondTrans.c.i

SecondTrans.s: SecondTrans.c.s
.PHONY : SecondTrans.s

# target to generate assembly for a file
SecondTrans.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/SecondTrans.c.s
.PHONY : SecondTrans.c.s

Table.o: Table.c.o
.PHONY : Table.o

# target to build an object file
Table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/Table.c.o
.PHONY : Table.c.o

Table.i: Table.c.i
.PHONY : Table.i

# target to preprocess a source file
Table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/Table.c.i
.PHONY : Table.c.i

Table.s: Table.c.s
.PHONY : Table.s

# target to generate assembly for a file
Table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/Table.c.s
.PHONY : Table.c.s

TxtFunc.o: TxtFunc.c.o
.PHONY : TxtFunc.o

# target to build an object file
TxtFunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/TxtFunc.c.o
.PHONY : TxtFunc.c.o

TxtFunc.i: TxtFunc.c.i
.PHONY : TxtFunc.i

# target to preprocess a source file
TxtFunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/TxtFunc.c.i
.PHONY : TxtFunc.c.i

TxtFunc.s: TxtFunc.c.s
.PHONY : TxtFunc.s

# target to generate assembly for a file
TxtFunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/TxtFunc.c.s
.PHONY : TxtFunc.c.s

assembler.o: assembler.c.o
.PHONY : assembler.o

# target to build an object file
assembler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler.c.o
.PHONY : assembler.c.o

assembler.i: assembler.c.i
.PHONY : assembler.i

# target to preprocess a source file
assembler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler.c.i
.PHONY : assembler.c.i

assembler.s: assembler.c.s
.PHONY : assembler.s

# target to generate assembly for a file
assembler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler.c.s
.PHONY : assembler.c.s

ext.o: ext.c.o
.PHONY : ext.o

# target to build an object file
ext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/ext.c.o
.PHONY : ext.c.o

ext.i: ext.c.i
.PHONY : ext.i

# target to preprocess a source file
ext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/ext.c.i
.PHONY : ext.c.i

ext.s: ext.c.s
.PHONY : ext.s

# target to generate assembly for a file
ext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/ext.c.s
.PHONY : ext.c.s

str.o: str.c.o
.PHONY : str.o

# target to build an object file
str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/str.c.o
.PHONY : str.c.o

str.i: str.c.i
.PHONY : str.i

# target to preprocess a source file
str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/str.c.i
.PHONY : str.c.i

str.s: str.c.s
.PHONY : str.s

# target to generate assembly for a file
str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/str.c.s
.PHONY : str.c.s

symTable.o: symTable.c.o
.PHONY : symTable.o

# target to build an object file
symTable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/symTable.c.o
.PHONY : symTable.c.o

symTable.i: symTable.c.i
.PHONY : symTable.i

# target to preprocess a source file
symTable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/symTable.c.i
.PHONY : symTable.c.i

symTable.s: symTable.c.s
.PHONY : symTable.s

# target to generate assembly for a file
symTable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/symTable.c.s
.PHONY : symTable.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... assembler"
	@echo "... FirstTrans.o"
	@echo "... FirstTrans.i"
	@echo "... FirstTrans.s"
	@echo "... SecondTrans.o"
	@echo "... SecondTrans.i"
	@echo "... SecondTrans.s"
	@echo "... Table.o"
	@echo "... Table.i"
	@echo "... Table.s"
	@echo "... TxtFunc.o"
	@echo "... TxtFunc.i"
	@echo "... TxtFunc.s"
	@echo "... assembler.o"
	@echo "... assembler.i"
	@echo "... assembler.s"
	@echo "... ext.o"
	@echo "... ext.i"
	@echo "... ext.s"
	@echo "... str.o"
	@echo "... str.i"
	@echo "... str.s"
	@echo "... symTable.o"
	@echo "... symTable.i"
	@echo "... symTable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

